### ISSUE TITLE
Revisit CORS issue

### ISSUE THREAD

**Issue by dankirkd** [aws-samples/aws-serverless-workshop-innovator-island#12]
I'm afraid that I cannot upload photos from the application due to CORS issues:

>Access to XMLHttpRequest at 'https://b3tduirkm1.execute-api.us-west-2.amazonaws.com/Prod/Upload' from origin 'https://master.d1scdwkrvbfu7c.amplifyapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I know you covered this at the beginning of Day 3, but I missed that due to other issues, so it would be nice if you could revisit that.

**Comment by jbesw** [comment]
Great - I'm glad that helped!

**Comment by dankirkd** [comment]
I've since set Cloud9 to auto-save after a short delay.

**Comment by jbesw** [comment]
Great idea!

**Comment by dankirkd** [comment]
https://theme-park-backend-finalbucket-1fshglqfvcp8n.s3.amazonaws.com/f2097515-2e6f-4b95-b332-e0ba85d133e3.jpg - Tried adjusting the HSV_LOWER value to 36,50,50 but that seems to be too much.

**Comment by dankirkd** [comment]
This looks better: https://theme-park-backend-finalbucket-1fshglqfvcp8n.s3.amazonaws.com/528456b3-8881-49fd-80e8-c7d37e056bb5.jpg - using 36,57,57

**Comment by jbesw** [comment]
Looks good! In a production use case, experimenting with the range of HSV values is important since lighting can effect the interpretation of the green background.
