### ISSUE TITLE
Everything runs without error but .jpg file has error

### ISSUE THREAD

**Issue by vfulco** [aws-samples/aws-serverless-workshop-innovator-island#14]
In Module #3: section 2...

When running the final test of this module, the .jpg won't open and gives 'error could not load image "green-screen-test.jpg" Error interpreting JPEG image file (not a jpeg file: starts with 0x89 0x50)'.

Please advise.  Thanks.

**Comment by jbesw** [comment]
That error indicates the file is a PNG, not a JPG, which indicates some of the processing steps have no happened.

Can you:
1. Check the contents of the upload, processing, and final buckets? You should find a PNG in the upload bucket and JPGs in the other two.
2. Check the Lambda logs for the chromakey and compositing functions to make sure they executed without errors?

Thanks,
James

**Comment by vfulco** [comment]
Thanks for the fast response.  Will do in next 24 hours and report back.
