### ISSUE TITLE
 new translations button 

### ISSUE THREAD

**Issue by norbuy12** [aws-samples/aws-serverless-workshop-innovator-island#17]
on the module 4
Push to CodeCommit and deploy via Amplify:
step no 2 & 3. 
where it says translations button should have appeared in the menu bar at the top of the display. I do not see anything except for the zoom in and zoom out button. I must have missed something out. I am new at this. Need help. Thanks

**Comment by jbesw** [comment]
Just check these two things:
1. After the git commit, ensure that one file changed (config.js) and after git push, you saw Amplify Console detect the change and deploy the new version.
2. Often the browser will cache an older version of the code. To ensure it is running the latest, do a hard refresh of the webpage (CTRL+F5 on Windows). This will load the latest version of the code.
Let me know if this helps!

**Comment by norbuy12** [comment]
It did. Thank you very much.

**Comment by jbesw** [comment]
Great to hear!
