### ISSUE TITLE
Deprecated uuid sintax in theme-park-backend-S3UploaderFunction

### ISSUE THREAD

**Issue by Montbra** [aws-samples/aws-serverless-workshop-innovator-island#18]
Running in module errors in this function. Per npm docs:

Deep Requires No Longer Supported
Deep requires like require('uuid/v4') which have been deprecated in uuid@7 is no longer supported.

Changes made in code:
//const uuidv4 = require('uuid/v4')
const { v4: uuidv4 } = require('uuid')

Redeploy and now works like a charm.

**Comment by jbesw** [comment]
Hi! This was a breaking change in UUID - we fixed the https://github.com/aws-samples/aws-serverless-workshop-innovator-island/blob/master/1-app-deploy/sam-app/getUploadURL/app.js code on Monday night, but many workshop attendees had already deployed the code. It's really unfortunate timing! Thanks for the comment.
