### ISSUE TITLE
User ID and Password request

### ISSUE THREAD

**Issue by awsome1-mtegrate** [aws-samples/aws-serverless-workshop-innovator-island#19]
I took a break from the workshop for a day and now when I run the command 'git push' I am being asked for a user ID and password and I have no idea which one to try

This is in the translate module

**Comment by julianwood** [comment]
Try redoing the CodeCommit git config in Module1:
git config --global credential.helper '!aws codecommit credential-helper $@'
git config --global credential.UseHttpPath true
cd ~/environment/theme-park-frontend/
AWS_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/\(.*\)[a-z]/\1/')
git push --set-upstream https://git-codecommit.$AWS_REGION.amazonaws.com/v1/repos/theme-park-frontend master

**Comment by awsome1-mtegrate** [comment]
Thanks - worked perfectly!
![image](https://user-images.githubusercontent.com/66848305/84554214-cf763780-ad0e-11ea-8f07-262d77265dad.png)
