### ISSUE TITLE
add to dashboard button

### ISSUE THREAD

**Issue by norbuy12** [aws-samples/aws-serverless-workshop-innovator-island#20]
on module 6.
step 3: Creating the dashboard
on the bullet point where it says: add to dashboard.
the button seems to be not working or something is wrong with it.
I did hard refresh to all the pages tried multiple times but no progess so far. 

![cloudwatch](https://user-images.githubusercontent.com/65431248/84551261-0f232c00-acdb-11ea-8b62-d203dae310fa.JPG)

**Comment by jbesw** [comment]
Click the small checkbox next to text field where you entered "InnovatorIsland" and this will enable the Add command button. HTH!

**Comment by norbuy12** [comment]
It worked. 
Thank you.
