### ISSUE TITLE
00-cleanup missing S3, ride-times stack

### ISSUE THREAD

**Issue by cgeisel** [aws-samples/aws-serverless-workshop-innovator-island#22]
Hey, just cleaning up after a great workshop last week and I noticed that the upload, processing, etc buckets need to be emptied before the associated Cloudformation stacks will delete. Also there was a stack that didn't have the "theme-park-" naming convention: ride-times.

**Comment by jbesw** [comment]
Thanks Chris! I've modified the clean-up instructions to address these issues: https://github.com/aws-samples/aws-serverless-workshop-innovator-island/blob/master/00-cleanup/README.md. Thanks for the feedback!

**Comment by NewWorldMan** [comment]
Looked like the DynamoDB instance got removed automatically in cleanup. Does that sound correct?


Barry Propes
Richardson, Tx
www.barrypropes.com
________________________________

**Comment by jbesw** [comment]
Barry - yes, there are two DynamoDB tables used in two stacks set up in module 1, so both will be removed when you delete those stack.

**Comment by NewWorldMan** [comment]
Thank you, James!


Barry Propes
Richardson, Tx
www.barrypropes.com
________________________________
