### ISSUE TITLE
Users all share same photo gallery

### ISSUE THREAD

**Issue by gregshep** [aws-samples/aws-serverless-workshop-innovator-island#3]
Are all the users supposed to share the same photo gallery?  Should Cognito be allowing for logins?  I did this workshop at re:Invent this year and again at home.  Did I implement something incorrectly?

**Comment by jbesw** [comment]
The photo gallery is unique to your AWS account (it's the photos contained in your final bucket, listed in the DynamoDB table). In the real world, the photo gallery would be a central resource where you use Cognito control access by user, but in the tutorial we are only focusing on the programmatic flow of the feature.
