### ISSUE TITLE
Step 1 - Amplify Console deployment fails at Build stage

### ISSUE THREAD

**Issue by alexcasalboni** [aws-samples/aws-serverless-workshop-innovator-island#36]
Hi,

I'm getting this error at the build stage when deploying the frontend:

> There was an issue connecting to your repo provider, click "Re-authenticate app" in General Settings, and then try your build again.

I've done that ("Reconnect repository"), but the same message appears again at the next deployment.

The frontend code has been pushed to CodeCommit correctly, and this seems like an IAM issue.

Any suggestions?

**Comment by alexcasalboni** [comment]
Update: it is an IAM issue with the Amplify Console service role.

The role had already been created for another project, in the same region but allowing access only to another specific CodeCommit repository. 

I'd expect Amplify Console to update this service role when creating a new app from a different repository.

**Comment by jbesw** [comment]
This is not an issue relating to the code in this repo - please reopen with the Amplify Console service.

**Comment by 023PrashantSharma** [comment]
> Update: it is an IAM issue with the Amplify Console service role.
> 
> The role had already been created for another project, in the same region but allowing access only to another specific CodeCommit repository.
> 
> I'd expect Amplify Console to update this service role when creating a new app from a different repository.

i am also facing same issue, how can i resolve this one
