### ISSUE TITLE
Step 1 - backend deployment (without a Layer)

### ISSUE THREAD

**Issue by alexcasalboni** [aws-samples/aws-serverless-workshop-innovator-island#37]
After deploying the backend stack in step 1, the documentation says:

> SAM has now used CloudFormation to deploy a stack of backend resources which will be used for the rest of the workshop, 2 x Lambda functions **and a Lambda Layer**, 3 x S3 buckets, a DynamoDBTable, Cognito UserPool, AWS IoT thing and a number of IAM Roles and Policies.

But there is no Lambda Layer in the stack. Is this a documentation error, or maybe we'll add it later?

It might be confusing for customers.

**Comment by jbesw** [comment]
Updated description to resolve.
