### ISSUE TITLE
Step 3 - eval in Lambda function code

### ISSUE THREAD

**Issue by alexcasalboni** [aws-samples/aws-serverless-workshop-innovator-island#43]
We're passing `HSV_LOWER` and `HSV_UPPER` a python tuples.

```python
lower_range = eval(os.environ["HSV_LOWER"])
upper_range = eval(os.environ["HSV_UPPER"])
```

I think this is not something we'd want to recommend in production.

I can think of two better options:

1. provide the values as a json list -> `[36, 100, 100]` instead of `(36, 100, 100)`, then simply `tuple(json.loads(os.environ["HSV_LOWER"]))`
2. Make these env variables optional and simply use the default values (no need to eval of json.loads)

**Comment by jbesw** [comment]
This has been resolved and merged by issue #49
