### ISSUE TITLE
Step 3 - final end-to-end test with png sample photo

### ISSUE THREAD

**Issue by alexcasalboni** [aws-samples/aws-serverless-workshop-innovator-island#44]
The "Add ride photo" button only accept jpg files:

```html
<input id="file" accept="image/jpeg" type="file" style="display: none;">
```

Because of this, I couldn't easily use the the provided png file named `green-screen-test.png` (from the browser, since I've been doing this workshop from home, without a real greenscreen).

If you just rename the file to `green-screen-test.jpg` it works fine, but I think this unnecessary friction. We could simply provide a jpg sample image, or simply use `accept="image/jpeg,image/png"` in the HTML.

**Comment by jbesw** [comment]
This has been resolved with merge #50. 

At the next frontend refresh in January, I'll add multiple upload types in the UI but for now this change in the README and the new JPG file resolves this issue.
