### ISSUE TITLE
Step 5 - Kinesis Firehose buffering conditions

### ISSUE THREAD

**Issue by alexcasalboni** [aws-samples/aws-serverless-workshop-innovator-island#46]
Because the simulation is generating 5MB of logs every 6-7 seconds, we could recommend customers to configure a larger buffering condition to minimize the # of S3 PUT requests.

Something like 10MB or 20MB?

**Comment by jbesw** [comment]
Addressed in latest commit - buffer changed to 10MB in instructions.
