### ISSUE TITLE
Step 3.2 - Lambda Access Denied

### ISSUE THREAD

**Issue by liannario** [aws-samples/aws-serverless-workshop-innovator-island#47]
Module 3.2: I had to remove `ACL: 'public-read'` from `outParams` in `/theme-park-backend/3-photos/2-compositing/lambdaFunction/app.js` otherwise the Lambda function was getting Access Denied error when writing to `$FINAL_BUCKET`.

**Comment by jbesw** [comment]
This occurs if you are using an account where S3 buckets do not allow access to public objects. I recommend using a new personal account for running workshops, or using an Event Engine account if you are at an AWS event.
