### ISSUE TITLE
Module 5 Incompatible QuickSight options

### ISSUE THREAD

**Issue by alan-churley** [aws-samples/aws-serverless-workshop-innovator-island#51]
Module 5: Analyzing visitor stats - (c) Configure and use QuickSight
Creating a QuickSight account

Step 3 says to select Standard Edition,
Step 4 says to `Leave Use Role Based Federation (SSO) selected.` this is however an enterprise feature, and the screenshot for this stage shows an enterprise setup.

Is enterprise needed, if so the Step 3 should be updated to reflect this

**Comment by jbesw** [comment]
Thanks - I've updated the instructions to remove "Leave *Use Role Based Federation (SSO)* selected." Only Standard Edition is needed.
