### ISSUE TITLE
Frontend Error

### ISSUE THREAD

**Issue by msailes** [aws-samples/aws-serverless-workshop-innovator-island#53]
There is an error logged in the browser console in what I think is normal operation. This has been confusing to customers who think that something is wrong. Screenshot attached.

Can this error be captured and logged as something else?

Thanks,

<img width="1041" alt="Screenshot 2021-01-27 at 11 49 31" src="https://user-images.githubusercontent.com/45629314/106009157-f4f25e80-60af-11eb-98bc-66c6eb201a04.png">

**Comment by jbesw** [comment]
This is normal and is generated by the SDK in between getting credentials for forming the connection. It has no side-effects on the application but I don't believe the frontend can suppress the message.

**Comment by jbesw** [comment]
Mark, good news! I've worked out a solution to this issue. In the next couple of weeks, I'll be applying a few updates to the workshop so I will patch the frontend code during that process.

**Comment by msailes** [comment]
Raising the bar.

**Comment by jbesw** [comment]
This error has now been resolved in the latest frontend.zip package.
