### ISSUE TITLE
UPLOAD_BUCKET variable not set in Module 3

### ISSUE THREAD

**Issue by nmoutschen** [aws-samples/aws-serverless-workshop-innovator-island#56]
**Describe the bug**

[Instructions in the module 3](https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend.html) only retrieve the AWS Region and final bucket, but not the upload bucket (which is needed for subsequent operations in this module. There are instructions in [module 1](https://www.eventbox.dev/published/lesson/innovator-island/1-deploy/3-backend.html) that sets this variable.

If I run module 3 at a subsequent time or in a new terminal, I won't have the `$UPLOAD_BUCKET` variable set properly.

Furthermore, instructions in the aforementioned paged ask the user to replace the bucket name manually (`aws s3 cp ./green-screen-test.png s3://youruploadbucketname`), while [the next section](https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend/2-compositing.html) uses that variable (`aws s3 cp ./green-screen-test.png s3://$UPLOAD_BUCKET`).

**Link to workshop URL**

https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend.html

**To Reproduce**
1. Create a new terminal window
2. Follow instructions in module 3
3. Get an error when testing the photo compositing Lambda function

**Expected behavior**

The `UPLOAD_BUCKET` should be set at the beginning of module 3.

**Screenshots**

**Desktop (please complete the following information):**
 - Cloud9

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by jbesw** [comment]
Thanks for raising this issue! https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend.html has now been updated.
