### ISSUE TITLE
Incorrect line numbers in Translation module (module 4)

### ISSUE THREAD

**Issue by stylesm** [aws-samples/aws-serverless-workshop-innovator-island#57]
**Describe the bug**
Line numbers referenced in instructions are incorrect in the Translation module.

**Link to workshop URL**
https://www.eventbox.dev/published/lesson/innovator-island/4-translate/2-backend.html#step-by-step-instructions

**To Reproduce**
In the text 

> Select your target languages. On line 36, the targetLanguages array shows a list of languages for translation. Currently this is set to French, Spanish and Japanese - you can modify this array to include of the supported language codes (show on line 29 in the possibleLanguages array). Choose 4-5 different languages.

the line numbers are incorrect.
Line 23 has the targetLanguages array.
Line 16 has the possibleLanguages array.

**Expected behavior**
Line 23 has the targetLanguages array.
Line 16 has the possibleLanguages array.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jbesw** [comment]
Thanks for raising this issue! https://www.eventbox.dev/published/lesson/innovator-island/4-translate/2-backend.html#step-by-step-instructions has now been updated.
