### ISSUE TITLE
Missing checkbox ticking instruction in Park Stats module (module 5)

### ISSUE THREAD

**Issue by stylesm** [aws-samples/aws-serverless-workshop-innovator-island#58]
**Describe the bug**
In the 'Configure and use QuickSight' instructions, there are instructions to uncheck 

**Link to workshop URL**
https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/3-quicksight.html#step-by-step-instructions

**To Reproduce**
1. Go to https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/3-quicksight.html#step-by-step-instructions
2. Scroll down to "4. In the next page in the sign-up process:"
3. Where the text says:
> Uncheck any checked boxes - this creates a popup.
This doesn't create a popup - checking 'S3 buckets' creates a popup.

**Expected behavior**
Text should read something like:
> Uncheck any checked boxes, then check the 'S3 buckets' checkbox - this creates a popup.

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
N/A

**Comment by jbesw** [comment]
Thanks for raising this issue! https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/3-quicksight.html#step-by-step-instructions has now been updated.
