### ISSUE TITLE
In QuickSight 'ride rating' visualisation, setting colour rating aggregation to 'Average' isn't possible

### ISSUE THREAD

**Issue by stylesm** [aws-samples/aws-serverless-workshop-innovator-island#59]
**Describe the bug**
In 'Building visualizations #4' (the tree map), aggregating rider rating by average isn't possible

**Link to workshop URL**
https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/3-quicksight/4-visual.html#step-by-step-instructions

**To Reproduce**
1. Go to https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/3-quicksight/4-visual.html#step-by-step-instructions
2. Follow instructions 1-9 to create the visual
3. In step 10, "Click the dropdown arrow next to the rating field in the well, select the Aggregate sub-menu and choose Average"
4. Observe that the only available options are 'Count' or 'Count distinct'.

**Expected behavior**
'Average' should be an option for rating aggregation. 

**Screenshots**
![image](https://user-images.githubusercontent.com/5602910/116401372-13890280-a823-11eb-9c7f-39c5f7e50c4d.png)

**Desktop (please complete the following information):**
- Windows 10

**Smartphone (please complete the following information):**
- Firefox 88.0

**Additional context**
N/A

**Comment by jbesw** [comment]
Thanks for raising this issue! https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/1-firehose.html has been updated with new instructions on converting the "rating" data type to an integer, which resolves this issue.
