### ISSUE TITLE
After creating the photo composting Lambda function and uploading image with same filename, the Lambda is not triggered

### ISSUE THREAD

**Issue by stylesm** [aws-samples/aws-serverless-workshop-innovator-island#60]
**Describe the bug**
After creating the photo composting Lambda function and uploading image with same filename as used to test the Chromakey Lambda function, the new composting Lambda is not triggered.

**Link to workshop URL**
https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend/2-compositing.html#step-by-step-instructions-2

**To Reproduce**
1. Go to https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend/2-compositing.html#step-by-step-instructions-2
2. After completing Step 4 ("Copy the local testing image to your upload bucket.")
3. In AWS Console open S3 bucket 'theme-park-backend-finalbucket'
4. Observe that the image is not present.
5. In AWS Console open the Lambda function, and Monitor tab
6. Observe that the Lambda was not triggered.

**Expected behavior**
The composting Lambda is triggered and an image is present in the finalbucket.

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**
Deleting the image used in the first Lambda test from the upload bucket, then re-uploading, resolves the issue.

**Comment by jbesw** [comment]
Once the trigger is configured, it will be invoked every time any object is uploaded, regardless of key name. I think what you might be seeing is the delay between the invocation and the logs being written to CloudWatch, which can take up to 30 seconds.
