### ISSUE TITLE
Workshop Cleanup Script

### ISSUE THREAD

**Issue by corwinjoy** [aws-samples/aws-serverless-workshop-innovator-island#61]
It would be great to have a cleanup script for this workshop. It took me quite a while to go through the 10 different areas and make sure everything was deleted (and I am still not sure I got everything).

**Comment by jbesw** [comment]
Thanks very much for the suggestion! We are limited on scripting that performs destructive actions, since we are careful not to delete resources from customer accounts, but I'll see if we can at least publish some CLI commands that can make this easier. 

Thanks for attending the workshop!

**Comment by jbesw** [comment]
I updated the cleanup section to use CLI commands whenever possible to make this process much faster. Unfortunately, we cannot automate deleting assets in customers accounts but hopefully this the process less onerous. Thanks once again for raising this.

**Comment by corwinjoy** [comment]
Thanks! Sounds good!
