### ISSUE TITLE
Environment Variables assumed to be set when calling sam commands in https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend/2-compositing.html

### ISSUE THREAD

**Issue by indranilbanerjee2014** [aws-samples/aws-serverless-workshop-innovator-island#66]
**Describe the bug**
In the workshop on the step 2-backend/2-compositing (full URL provided below), the following commands assume environment variables to be already set

sam build

sam package --output-template-file packaged.yaml --s3-bucket $s3_deploy_bucket

sam deploy --template-file packaged.yaml --stack-name theme-park-photos --capabilities CAPABILITY_IAM --parameter-overrides "FinalBucketName"=$FINAL_BUCKET

When I was going through this lab, neither the $s3_deploy_bucket nor the $FINAL_BUCKET were set, so the command failed. I had to manually set these variables and re-run the commands. It is possible that the variables may have been set in an earlier step, but if Cloud9 has to be re-started because of auto-logout, all environment variable settings are lost. It will be good to add a step so set the variables before they are actually used.

**Link to workshop URL**
https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend/2-compositing.html

**To Reproduce**
1. Before doing the step in the URL above, log out of the account.
2. Log back in and restart Cloud9
3. Then try running this part of the lab with the sam commands described above

**Expected behavior**
The variables $s3_deploy_bucket and $FINAL_BUCKET need to be reset just before being used in the sam commands, even if they were set earlier

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbesw** [comment]
Thanks for reporting! To mitigate issues with customers restarting Cloud9 or opening new terminals, we have added an informational dialog in the "Set up environment variables" step that explains this issue. We have avoided setting environment variables before every sam command to keep the instructions clearer.
