### ISSUE TITLE
The Instruction Site for Serverless workshop Innovator-island

### ISSUE THREAD

**Issue by kakaspire** [aws-samples/aws-serverless-workshop-innovator-island#67]
**Describe the bug**
There are some inconsistencies in the serverless innovator island workshop.
1. The description "The Flow & Traffic Controller exists in a separate AWS account owned by the theme park. You are provided with the SNS topic ARN to use." in the chapter of "2. Real-time ride wait times - > Backend" seems not correct, need to be rephrase.  

The reason is that the lambda "theme-park-ride-times-UpdateRides" is created  in the step of "1. Deploy the application - > Backend" to update the Rides information to SNS Topic "theme-park-ride-times-FATcontroller",   and the topic is subscribed by another lambda; this is why I think the current description is not correct.  Further more,  Though "theme-park-ride-times-UpdateRides" is created, it's not mentioned in the architecture diagram.

**Link to workshop URL**
https://www.eventbox.dev/published/lesson/innovator-island/

**To Reproduce**
1. Go to 'https://www.eventbox.dev/published/lesson/innovator-island/'
2. Click on '2. Real-time ride wait times'
3. Click the sub menu "Backend"
3. Scroll down to  the architecture diagram 'Real-time Serverless Backend' and find the sentence "_The Flow & Traffic Controller exists in a separate AWS account owned by the theme park. You are provided with the SNS topic ARN to use._"
4. The sentence is not correct, as the "Flow & Traffic Controller" should be in the same account and should already be created in the previous step of "1. Deploy the application"  in this workshop instructor. 

**Expected behavior**
The wrong description should be corrected as "A lambda named 'theme-park-ride-times-UpdateRides-XXXXXXXX' is already created in step 1 in the same account and it is triggered by EventBridge(CloudWatch Event) every minute to publish updates  to an Amazon SNS topic."

In the meanwhile, It would be good if the CloudWatchEvent and Lambda of UpdateRides can be reflected on the architecture diagrams. 

**Screenshots**
<img width="945" alt="Screen Shot 2021-09-27 at 6 12 23 PM" src="https://user-images.githubusercontent.com/79987998/134889934-ad935c54-1b66-4293-bc22-260ba94cee81.png">
<img width="885" alt="Screen Shot 2021-09-27 at 6 13 04 PM" src="https://user-images.githubusercontent.com/79987998/134890102-fcd82b25-1384-4726-808b-172d46c1d7a3.png">

**Comment by jbesw** [comment]
Thanks for reporting - I've updated the content.
