### ISSUE TITLE
Creating Firehose create wizard page is out of date 

### ISSUE THREAD

**Issue by peterjgrainger** [aws-samples/aws-serverless-workshop-innovator-island#69]
**Describe the bug**
Creating Firehose create wizard page is out of date 

**Link to workshop URL**
(https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/1-firehose.html)

**Comment by jbesw** [comment]
Thanks for reporting! I update the UI/instructions quarterly, so I'll update this in January 2022.

**Comment by jbesw** [comment]
I have refreshed module 5 with the latest UI screenshots and updated instructions throughout.
