### ISSUE TITLE
Is the backend code anywhere?

### ISSUE THREAD

**Issue by cjuega** [aws-samples/aws-serverless-workshop-innovator-island#75]
**Describe the bug**

I'm able to get the frontend code using the command indicated in the workshop:

```
wget https://innovator-island.s3-us-west-2.amazonaws.com/front-end/theme-park-frontend-202110.zip
```

That downloads the VUE app, but I can't figure out how to get the backend code. It isn't stated in the workshop either (https://www.eventbox.dev/published/lesson/innovator-island/1-deploy/3-backend.html).

It looks to me frontend and backend code used to be together. But that isn't the case anymore. Could that be?

How could I get access to the backend's SAM project?

**Link to workshop URL**
[A link to the workshop URL with the issue.](https://www.eventbox.dev/published/lesson/innovator-island/0-introduction.html)

**Comment by orozcoadrian** [comment]
The setup step says to clone this repo. I don't think there's a need to use `wget`. For example here's the backend code for step 1: https://github.com/aws-samples/aws-serverless-workshop-innovator-island/blob/main/1-app-deploy/sam-app/getInitState/app.js

https://www.eventbox.dev/published/lesson/innovator-island/0-setup/3-aws-cloud9-ide.html

**Comment by jbesw** [comment]
Hi, as @orozcoadrian indicates in his link, the backend is covered separately in the setup section of the workshop.
