### ISSUE TITLE
Workshop Feedback

### ISSUE THREAD

**Issue by ischia-exigenter** [aws-samples/aws-serverless-workshop-innovator-island#78]
Hi, I recently completed most of this workshop. I wanted to give some feedback to James and the team. First, thank you for producing workshops and introducing new AWS developers to Serverless. That said, there are a couple things I wish had been done differently.

The workshop has far too much clickops in the AWS Console. I cringed every time we were asked to run a command and then copy and past the value somewhere else. This is an unacceptable strategy, especially for a beginner workshop. We need everyone learning the right way to develop IaC. Please don't reinforce bad practices. My wish is that this whole workshop be redone without a single input step using the AWS Console. You know what the console is good for, reading CloudWatch logs.

The other area where this workshop lost me was QuickSight. Serverless developers are not the audience for QuickSight. I can only guess that some upper management type insisted that James include the most poorly performing AWS product in the workshop to artificially boost a utilization metric. 

Anyways, I hope no one's ego has been damaged by my feedback here. I'm the first to praise good work in person, and I only have the guts to criticize anyone if I can remain anonymous. So it is.

**Comment by jbesw** [comment]
As an AWS employee, please contact me directly on Slack to discuss.
