### ISSUE TITLE
Invalid cleanup step instruction

### ISSUE THREAD

**Issue by kozlov-nikita** [aws-samples/aws-serverless-workshop-innovator-island#80]
**Describe the bug**
In Cleanup section Step 7 (Kinesis Firehose) script
```
aws kinesis delete-stream --stream-name theme-park-streaming-data
```
does not work.

Instead working one:
```
aws firehose delete-delivery-stream --delivery-stream-name theme-park-streaming-data
```

**Link to workshop URL**
[A link to the workshop URL with the issue.](https://www.eventbox.dev/published/lesson/innovator-island/9-cleanup/1-overview.html#7-kinesis-firehose)

**To Reproduce**
1. execute
```
aws kinesis delete-stream --stream-name theme-park-streaming-data
```

Output:
```
An error occurred (ResourceNotFoundException) when calling the DeleteStream operation: Stream theme-park-streaming-data under account XXX not found.
```

**Expected behavior**
Successful resource deletion.

**Desktop (please complete the following information):**
 - Cloud9 virtual environment 
 - t3.small
 - us-east-1
 - pre installed:
```
aws-cli/1.19.112 Python/2.7.18 Linux/4.14.273-207.502.amzn2.x86_64 botocore/1.20.112
```

**Comment by jbesw** [comment]
Thanks, this has been updated and will be published on the next build.

**Comment by jbesw** [comment]
Checking this, the existing instruction has worked during my run-through. Please verify that your Kinesis stream type and name were the same as in the instructions. If you continue to have a problem, please contact me to troubleshoot. I'll close for now.
