### ISSUE TITLE
Points on map entry data abnormality

### ISSUE THREAD

**Issue by camyorke** [aws-samples/aws-serverless-workshop-innovator-island#81]
**Describe the bug**
When following the steps and applying the entry event filter, data is isolated only to a small part of the south of the USA and clumped in one bunch. This does not align with the screenshot provided in the module.

**Link to workshop URL**
(https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/3-quicksight/2-visual.html)

**To Reproduce**
1. Following the steps exactly as described in BUILDING VISUALIZATIONS 2

**Expected behavior**
Data is expected to be scattered around various parts of USA (as per screenshot on eventbox). However, when applying the filter for "entry" events only, data is isolated to just the south of USA (see attached screenshot below).

**Screenshots**

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/89069114/168516373-28114a0d-0901-4c94-bf39-f9e9a6202ab2.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1
 - Browser: Chrome
 - Version: Version 101.0.4951.64 (Official Build) (x86_64)

**Additional context**

**Comment by jbesw** [comment]
Hello! QuickSight displays only the top 10,000 data points in the visualization, so this can occur if there are more, and it selects 10,000 from the same Region. As a result, it will not show all the data points across the entire map.

**Comment by camyorke** [comment]
Thank you. Will this always be the outcome if the steps in the lab are followed? If so, could the screenshot be updated so it doesn’t cause confusion in future workshops please?

Thanks,
Cam

--
Cameron Yorke
Technical Account Manager | AWS Enterprise Support
+61.412.155.455

From: James Beswick ***@***.***>
Reply to: aws-samples/aws-serverless-workshop-innovator-island ***@***.***>
Date: Tuesday, 17 May 2022 at 3:00 am
To: aws-samples/aws-serverless-workshop-innovator-island ***@***.***>
Cc: "Yorke, Cameron" ***@***.***>, Author ***@***.***>
Subject: Re: [aws-samples/aws-serverless-workshop-innovator-island] Points on map entry data abnormality (Issue #81)


Hello! QuickSight displays only the top 10,000 data points in the visualization, so this can occur if there are more, and it selects 10,000 from the same Region. As a result, it will not show all the data points across the entire map.

**Comment by jbesw** [comment]
Yes, we will update the screenshot in the next maintenance window. Thanks for reporting!

**Comment by camyorke** [comment]
Excellent, thank you!

--
Cameron Yorke
Technical Account Manager | AWS Enterprise Support
+61.412.155.455

From: James Beswick ***@***.***>
Reply to: aws-samples/aws-serverless-workshop-innovator-island ***@***.***>
Date: Friday, 20 May 2022 at 5:12 am
To: aws-samples/aws-serverless-workshop-innovator-island ***@***.***>
Cc: "Yorke, Cameron" ***@***.***>, Author ***@***.***>
Subject: Re: [aws-samples/aws-serverless-workshop-innovator-island] Points on map entry data abnormality (Issue #81)


Yes, we will update the screenshot in the next maintenance window. Thanks for reporting!

**Comment by jbesw** [comment]
Thanks, this section has now been updated at https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/3-quicksight/2-visual.html.
