### ISSUE TITLE
Update Instructions to Prevent Variable Error message

### ISSUE THREAD

**Issue by jessegut14** [aws-samples/aws-serverless-workshop-innovator-island#82]
**Describe the bug**
In section 5, as we are instructed to run the simulator, we are told to run the command in the fourth step: 
```sam package --output-template-file packaged.yaml --s3-bucket $s3_deploy_bucket```

The issue I ran into running this command is that there was no previous direction to set the *s3_deploy_bucket*. This resulted in a command failing to run. 

I think having a step on setting that step would help if anyone runs into this problem

**Link to workshop URL**
https://www.eventbox.dev/published/lesson/innovator-island/5-parkstats/2-simulator.html

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbesw** [comment]
Hello! Currently the workshop assumes you are working through the modules sequentially and doing it one sitting, so the variable is set in earlier modules. We will update the instructions so the variable is set at the beginning of this module too. Thanks for reporting.

**Comment by jbesw** [comment]
In the module 5 overview, there is a section called "Set up environment variables". If you follow this, the $s3_deploy_bucket variable will be set. Any time you change terminal or restart Cloud9, you will need to reset environment variables.
