### ISSUE TITLE
Error while trying to configure environment variables

### ISSUE THREAD

**Issue by sumuhans** [aws-samples/aws-serverless-workshop-innovator-island#86]
**Describe the bug**
In the theme park exercise, under "1. Deploy the application" , on the "Bankend" page, I ran the following command

```
AWS_REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/\(.*\)[a-z]/\1/')
FINAL_BUCKET=$(aws cloudformation describe-stack-resource --stack-name theme-park-backend --logical-resource-id FinalBucket --query "StackResourceDetail.PhysicalResourceId" --output text)
PROCESSING_BUCKET=$(aws cloudformation describe-stack-resource --stack-name theme-park-backend --logical-resource-id ProcessingBucket --query "StackResourceDetail.PhysicalResourceId" --output text)
UPLOAD_BUCKET=$(aws cloudformation describe-stack-resource --stack-name theme-park-backend --logical-resource-id UploadBucket --query "StackResourceDetail.PhysicalResourceId" --output text)
DDB_TABLE=$(aws cloudformation describe-stack-resource --stack-name theme-park-backend --logical-resource-id DynamoDBTable --query "StackResourceDetail.PhysicalResourceId" --output text)
echo $FINAL_BUCKET
echo $PROCESSING_BUCKET
echo $UPLOAD_BUCKET
echo $DDB_TABLE
```

And I got the following error

`An error occurred (ValidationError) when calling the DescribeStackResource operation: Resource FinalBucket does not exist for stack theme-park-backend`

**Link to workshop URL**
A link to the workshop URL with the issue.
https://www.eventbox.dev/published/lesson/innovator-island/1-deploy/3-backend.html

**To Reproduce**
1. Follow all steps until you reach https://www.eventbox.dev/published/lesson/innovator-island/1-deploy/3-backend.html
2. Continue all the way until you reach "8. Configure environment variables."
3. Execute the command in that section

**Expected behavior**
No error
**Screenshots**
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/39094976/213867503-f839c8c7-8c80-4883-ba12-a5f76dc672b6.png">

**Desktop (please complete the following information):**
 - OS: [ Mac OS 12.6.1]
 - Browser [ chrome]
 - Chrome [Version 108.0.5359.124 (Official Build) (arm64)]

**Comment by pputhran** [comment]
@sumuhans -  Could you please double check if both the SAM templates on this page were deployed correctly? I have usually seen this error when one of the SAM templates was not deployed.  Please ensure both `theme-park-ride-times` on Step 5 and `theme-park-backend` on Step 7 is deployed and let us know.

**Comment by sumuhans** [comment]
Thanks so much Pawan for the prompt response, I have done the clean up and will do this from scratch probably this weekend. I will pay particular attentions to the SAM templates and see if this happens again and let you know the results
