### ISSUE TITLE
Lambda function "theme-park-photos-CompositeFunction" is returning an AccessDenied error

### ISSUE THREAD

**Issue by victorshinya** [aws-samples/aws-serverless-workshop-innovator-island#88]
**Describe the bug**
When you upload the test PNG image to S3 bucket "UploadBucket", the Lambda function "theme-park-photos-CompositeFunction" returns an Invoke Error (check CloudWatch logs).

CloudWatch log:
```
{
    "errorType": "AccessDenied",
    "errorMessage": "Access Denied",
    "code": "AccessDenied",
    "message": "Access Denied",
    "region": null,
    "time": "2023-02-24T18:54:18.237Z",
    "requestId": "G9B1CCWSQ9TV3BM9",
    "extendedRequestId": "5E1vQEwjZponfBIz9wg11NbdHr87Bkb81poNVSk+6qztJ805F5TSATDLu1JRTk+cSvmPs2EHyHw=",
    "statusCode": 403,
    "retryable": false,
    "retryDelay": 27.787428612758667,
    "stack": [
        "AccessDenied: Access Denied",
        "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/s3.js:711:35)",
        "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:688:12)",
        "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}
```

**Link to workshop URL**
https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend.html

**To Reproduce**
1. Go to the Workshop URL
2. Create the Lambda function using SAM 
3. Add the S3 trigger to the Lambda function
4. Test the function by uploading the test PNG image
5. Check the error on CloudWatch logs in "CompositeFunction" log group

**Expected behavior**
The Lambda function should create a photo compositing and upload to S3 bucket "FinalBucket".

**Screenshots**
Not applicable. I included the CloudWatch logs in "Describe the bug" section.

**Desktop (please complete the following information):**
 - Device: MacBook Pro (13-inch, 2020)
 - OS: macOS Monterey Version 12.6.3
 - Browser Google Chrome 
 - Version 109.0.5414.119 (Official Build) (x86_64)

**Additional context**
No additional context.

**Comment by machafer** [comment]
@victorshinya, thanks for raising this. Starting in April 2023 Amazon S3 will change the default security configuration for all new S3 buckets. You can find more information [here](https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/). We're working to fix this in the workshop. In the meantime, you can disable Block Public Access to the S3 bucket.

**Comment by victorshinya** [comment]
Ok! Thank you!
