### ISSUE TITLE
Is the "Out of service" normal behavior ?

### ISSUE THREAD

**Issue by ecukalla** [aws-samples/aws-serverless-workshop-innovator-island#89]
**Describe the bug**
When following the guide till [Update the fronted](https://www.eventbox.dev/published/lesson/innovator-island/1-deploy/4-update.html) of section 1 the output that I get is the following screenshot.

Are the "Out of service" in the screenshot reported correctly, as when viewing the youtube video those are not present, or is it due to smth I might have done wrong?

**To Reproduce**
follow along till the section 1.4 [here](https://www.eventbox.dev/published/lesson/innovator-island/1-deploy/4-update.html)

**Screenshots**
![Screenshot 2023-03-18 at 11 43 07 PM](https://user-images.githubusercontent.com/775064/226144194-26f600c2-e2a9-4b2c-be16-73def6c59206.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - Version 111.0.5563.64

**Comment by jbesw** [comment]
Hello! Yes this is normal. You will add the ride times in the next nodule which is about publishing realtime data back to he frontend. HTH!

**Comment by ecukalla** [comment]
A lot.

It would be nice for each step to have a screenshot of what the website looks before continuing to the next step. I can open this a feature request if needed and also contribute @jbesw .

**Comment by jbesw** [comment]
Yes I'll add to the backlog but pls feel free to submit any PRs and the team can review. Thanks for helping!
