### ISSUE TITLE
AWS Serverless Web App for a theme park Cloud 9 error

### ISSUE THREAD

**Issue by nick171451** [aws-samples/aws-serverless-workshop-innovator-island#91]
![Screenshot (896)](https://user-images.githubusercontent.com/129136720/228116147-dfe38c65-0e80-4584-98c2-b493903c4766.png)
![Screenshot (898)](https://user-images.githubusercontent.com/129136720/228116151-b84477c3-1797-4391-8644-d1be03370459.png)

While trying to push the downloaded code to populate your recently created CodeCommit repository i got this error: fatal: unable to access 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/theme-park-frontend/': The requested URL returned error: 403

**Comment by jbesw** [comment]
Can you paste your entire terminal? Often we see this if customer skip the first couple of instructions here: https://www.eventbox.dev/published/lesson/innovator-island/1-deploy/2-frontend.html at "2. Clone the code base". There are two git configuration commands.
