### ISSUE TITLE
Serverless workshop documentation, missing code details in Lab3 step 8

### ISSUE THREAD

**Issue by Prismahacker77** [aws-samples/aws-serverless-workshop-innovator-island#92]
**Describe the bug**
Lab 3, CREATING THE CHROMA KEY LAMBDA FUNCTION
Step 8, where is the code for the Lambda function.
Documentation says:
"Copy the code from the file in Cloud9 by navigating to 3-photos/1-chromakey/app.py onto the clipboard and paste into the lambda_function.py tab in the Lambda function:"

**Link to workshop URL**
[A link to the workshop URL with the issue.](https://www.eventbox.dev/published/lesson/innovator-island/3-photos/2-backend/1-chromakey.html)

**To Reproduce**
1. Go to 'CREATING THE CHROMA KEY LAMBDA FUNCTION'
2. Click on 'Step 8 with retrieving the code from a photo directory'

**Expected behavior**
Details as to where its located

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbesw** [comment]
Hello! On Cloud9, if you open the file explorer navigation on the left, drill down to the directory 3-photos/1-chromakey and open app.py to find the code.

**Comment by pputhran** [comment]
Please let us know if you are still experiencing the problem. Closing this one
