### ISSUE TITLE
The web page is shaky on the title screen

### ISSUE THREAD

**Issue by PrimaShella** [aws-samples/aws-serverless-workshop-innovator-island#93]
**Describe the bug**
Somehow the page is always shaky when opening the title page when opening 2 tabs at the same window

**Link to workshop URL**
A link to the workshop URL with the issue.
https://catalog.us-east-1.prod.workshops.aws/event/dashboard/en-US/workshop/91-report

**To Reproduce**
1. Go to any last section page
2. Click next page
3. The section will be shaky

**Expected behavior**
The page should not be shaky

**Screenshots**
[Screencast from 12-04-23 11:49:24.webm](https://user-images.githubusercontent.com/19583692/231353127-1765c707-6971-4266-9e3a-f51bf3b1de01.webm)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.02
 - Browser: Chrome
 - Version 112.0.5615.49 (Official Build) (64-bit)

**Additional context**

**Comment by jbesw** [comment]
Hello! This is an issue with Workshop Studio and not the workshop itself, so I've passed this over to that team and will close on this repo. Thanks for reporting!
