### ISSUE TITLE
Idempotency issue in AWS Lambda function handling EventBridge target

### ISSUE THREAD

**Issue by NullPointer4096** [aws-samples/aws-serverless-workshop-innovator-island#94]
**Description**
The current AWS Lambda function is designed to publish ride wait time data to Amazon CloudWatch Metrics. However, there's a potential idempotency issue that might lead to duplicate metric data being sent to CloudWatch Metrics if the Lambda function is re-invoked with the same input.

**Steps to reproduce**
1. The Lambda function is triggered by an EventBridge event containing ride wait time data.
2. The function processes the message and publishes the metric data to CloudWatch Metrics.
3. An error occurs, causing the Lambda function to fail.
4. The Lambda function is retried with the same input message.
5. The same metric data is sent to CloudWatch Metrics again, causing duplication.

**Expected Behavior**
The Lambda function should be idempotent, ensuring that the same metric data is not sent to CloudWatch Metrics multiple times, regardless of any exceptions, errors, or retries.

**Actual Behavior**
If an error occurs during the execution of the Lambda function, it may cause the function to be retried with the same input, leading to duplicate metric data being sent to CloudWatch Metrics.

**Suggested fix**
To resolve this issue, we can implement a unique identifier for each event and use the DedupeString parameter while sending the event to EventBridge. This will ensure that EventBridge discards duplicate events with the same deduplication string within a 24-hour period.

By implementing these checks, the Lambda function can ensure idempotent behavior in the face of transient failures and retries.

Thank you for your contribution to the Github community and I really appreciate your effort in following through this issue.

**Comment by jbesw** [comment]
Given the nature of the metrics published, these do not need to be idempotent for the sake of this workshop.
